version: "3.1"
services:
  python:
    image: 'img-search:v2'
    container_name: python
    hostname: python
    privileged: true
    restart: always
    working_dir: /docker/python-img-search
    command: ["python","searchServer.py"]
    ports:
      - "5555:5555"
    volumes:
      - '/docker/wwwroot/python-img-search:/docker/python-img-search'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
