version: "3.1"
services:
  python:
    image: 'ppp:v3'
    container_name: python
    hostname: python
    privileged: true
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - 'E:\www\yzh\towhee-img-search:/docker/hyperf'
